---

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'ubuntu'

- include_tasks: v1.yml

  # -----Nginx comman taks----

  # create and copy nginx conf file

- name: copy nginx conf file
  template: 
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - reload_nginx
  

  # start and enable

- name: configure and running
  service:
    name: nginx
    state: started
    enabled: true