---
- name: update apt
  apt: 
    update_cache: yes

- name: remove older version if exists
  package:
    name: 
      - docker
      - docker-engine
    state: absent

- name: set Up repo
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
    state: present
  
- name: Add Docker’s official GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present


- name: add-apt-repository
  apt_repository:
      repo : "deb [arch=amd64] https://download.docker.com/linux/ubuntu/ {{ ansible_distribution_release }} stable"
      state: present
      update_cache: true