---
- name: update apt
  apt: 
    update_cache: yes

- name: remove older version if exists
  package:
    name: 
      - docker
      - docker-engine
    state: absent

- name: set Up repo
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present