---
- name: run second version
  docker_container:
    name: go-v2
    image: mabdollahzae/go-apps:v2.0.0
    ports: "{{ new_app_port }}:3000"
    state: started
  
- name: health check on new deployed docker_container
  uri: 
    url: "{{ 'http://' + {{ host_ip }}:{{ new_app_port }}{{ app_healthcheck_path }} }}"
    method: GET
    status_code: 200
  retries: 10
  delay: 5
  register: _app_healthcheck_result



- debug:
  msg : {{ _app_healthcheck_result }}

    
